### PR TITLE
Reservation Endpoints

### PR DESCRIPTION
**Pull request by bushmusi**
# Hi Team

## Features added

1. Fetching reservation list
2. Creating a reservation list

### CODE REVIEW

**Review by mwafrika — CHANGES_REQUESTED** [review]
Hi @bushmusi 
You are almost there! It's good if you can implement the delete reservation and the reservation detail. that's all

**Comment by bushmusi** [comment]
> Hi @bushmusi You are almost there! It's good if you can implement the delete reservation and the reservation detail. that's all

Hi @mwafrika , You mentioned the right point am going to implement it now. Thanks

**Comment by mwafrika** [comment]
Alright @bushmusi  Good luck man

**Comment by bushmusi** [comment]
Hi @mwafrika, Can you check it now I added the feature of `delete` endpoint

**Review by mwafrika — CHANGES_REQUESTED** [review]
Hi @bushmusi
You are almost there, well done implementing the delete endpoint! It's good if you can implement the reservation detail (show) API. so that the user can see a single reservation

**Review by mwafrika — APPROVED** [review]
# Status Approved :green_circle: 

### You have done a great job building `Reservation API`. There is nothing but it is time to merge it :smile: 

- [x] No linter error
- [x] Followed RoR best practice
- [x] Professional comment
- [x] DRY code

**Pull request merged**
